const names = [
    "Emma",
    "Liam",
    "Olivia",
    "Noah",
    "Ava",
    "Elijah",
    "Sophia",
    "William",
    "Isabella",
    "James",
    "Mia",
    "Benjamin",
    "Charlotte",
    "Lucas",
    "Amelia",
    "Oliver",
    "Harper",
    "Alexander",
    "Evelyn",
    "Ethan",
    "Abigail",
    "Michael",
    "Emily",
    "Daniel",
    "Elizabeth",
    "Henry",
    "Sofia",
    "Matthew",
    "Avery",
    "Joseph",
    "Ella",
    "David",
    "Scarlett",
    "Andrew",
    "Grace",
    "Joshua",
    "Chloe",
    "Christopher",
    "Victoria",
    "Nathan",
    "Riley",
    "Samuel",
    "Aria",
    "Aiden",
    "Lily",
    "Mason",
    "Aubrey",
    "Logan",
    "Zoey",
    "Leo",
    "Penelope",
    "Jack",
    "Layla",
    "Gabriel",
    "Nora",
    "Ryan",
    "Hannah",
    "Lucas",
    "Lillian",
    "John",
    "Addison",
    "Isaac",
    "Stella",
    "Caleb",
    "Bella",
    "Luke",
    "Natalie",
    "Anthony",
    "Zoe",
    "Isaiah",
    "Leah",
    "Eli",
    "Hazel",
    "Aaron",
    "Violet",
    "Connor",
    "Aurora",
    "Jeremiah",
    "Savannah",
    "Charles",
    "Audrey",
    "Josiah",
    "Brooklyn",
    "Jordan",
    "Claire",
    "Jonathan",
    "Skylar",
    "Adrian",
    "Lucy",
    "Camden",
    "Eleanor",
    "Wyatt",
    "Paisley",
  ];
  
  const thought = [
    "The journey of self-discovery is the key to happiness and fulfillment.",
    "Kindness and empathy have the power to change the world.",
    "Cherish the little moments, for they become precious memories.",
    "In nature, we find the beauty of simplicity and the peace of mind.",
    "Music has the ability to touch our souls and connect us all.",
  ];
  
  const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];
  
  const getRandomName = () => `${getRandomArrItem(names)} ${getRandomArrItem(names)}`;
  
  const getRandomThought = () => `${getRandomArrItem(thought)}`;
  
  module.exports = { getRandomName, getRandomThought };
  